### ISSUE TITLE
Crash when API is down

### ISSUE THREAD

**Issue by detohm** [finnomena/CryptoSpace#3]
Not sure whether other users are facing the same issue. It threw an error pop-up and crashed while the BX's API was down.

**Comment by pitchmak** [comment]
not sure is it because of error handling or creating .app process. I'll check it ASAP.

**Comment by pitchmak** [comment]
I've improved error handling on a03f07e7b05e9ffb4c19b3f8e4842ec575ee5a48, let me know if this issue still occurs.

**Comment by pitchmak** [comment]
Finally, I can test when BX is unavailable. It returns html while we want json format. Fixed on 7cf2c342bd9c950da9480dd280df52a37e63fc22
